DROP TABLE IF EXISTS BOOKS_COMMENTS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS COMMENTS;
DROP TABLE IF EXISTS BOOKS;
CREATE TABLE AUTHORS(ID BIGINT AUTO_INCREMENT PRIMARY KEY, F_NAME VARCHAR(255), L_NAME VARCHAR(255));
CREATE TABLE GENRES(ID BIGINT AUTO_INCREMENT PRIMARY KEY, GENRE VARCHAR(255));
CREATE TABLE COMMENTS(ID BIGINT AUTO_INCREMENT PRIMARY KEY, MESSAGE VARCHAR(1000), DATE_MESSAGE DATE);
CREATE TABLE BOOKS(ID BIGINT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(255), ID_AUTHOR BIGINT, ID_GENRE BIGINT, ID_COMMENT BIGINT, FOREIGN KEY (ID_AUTHOR) REFERENCES AUTHORS(ID),
FOREIGN KEY (ID_GENRE) REFERENCES GENRES(ID), FOREIGN KEY (ID_COMMENT) REFERENCES COMMENTS(ID));
CREATE TABLE BOOKS_COMMENTS(ID_BOOK BIGINT NOT NULL,ID_COMMENT BIGINT NOT NULL, FOREIGN KEY (ID_BOOK) REFERENCES BOOKS(ID), FOREIGN KEY (ID_COMMENT) REFERENCES COMMENTS(ID) ON DELETE CASCADE);
