DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS BOOKS;
CREATE TABLE AUTHORS(ID BIGINT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(255));
CREATE TABLE GENRES(ID BIGINT AUTO_INCREMENT PRIMARY KEY, GENRE VARCHAR(255));
CREATE TABLE BOOKS(ID BIGINT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(255), ID_AUTHOR BIGINT, ID_GENRE BIGINT, FOREIGN KEY (ID_AUTHOR) REFERENCES AUTHORS(ID),
FOREIGN KEY (ID_GENRE) REFERENCES GENRES(ID));
